### PR TITLE
Update to HDF 1.10.2

### PR DESCRIPTION
**Pull request by Apollo3zehn**
I created a fork from your master, merged this with the HDFGroup/PInvoke master to keep up with gheber's changes and resolved minor conflicts in the following files:
- README.md
- RELEASE_NOTES.md
- UnitTests\UnitTests.csproj

I also updated the linux binaries to 1.10.2 (taken from https://www.hdfgroup.org/downloads/hdf5/).

No matter if you will merge this pull request or prefer to merge with the upstream master by yourself, I am eager to see HDF P/Invoke 1.10.2 available for .NET Standard because it solves three problems at once in my application :) Thanks for your work so far!

### CODE REVIEW

**Comment by Apollo3zehn** [comment]
The linux test is failing. I copied the file `hdf5\lib\libhdf5.so.101.1.0` of tarball `hdf5-1.10.2-Std-centos7-x86_64-shared_64.tar.gz` and renamed it to `libhdf5.so`. I am not experienced with Linux, maybe I need to change somthing else in the H5DLLImporter? 

@surban, do you have an idea what is going on here?

Error Message:
```
Class Initialization method UnitTests.H5ATest.ClassInit threw exception. 
System.TypeInitializationException: System.TypeInitializationException: 
The type initializer for 'HDF.PInvoke.H5P' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'HDF.PInvoke.H5DLLImporter' threw an exception. 
---> System.DllNotFoundException: Unable to load DLL 'hdf5': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E).
```

**Comment by surban** [comment]
Yes, the new `libhdf5.so` depends on `libsz.so.2`, which is missing.
On Linux you can check .so dependencies with the `ldd` command.
Ubuntu on Windows will do the trick, if you don't have a Linux machine around.

```
surban@mint3 ~/dev/HDF.PInvoke $ ldd native/HDF5_1.10/linux64/libhdf5.so
        linux-vdso.so.1 (0x00007fff3d4b1000)
        libsz.so.2 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f72f5e29000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f72f5c25000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f72f5887000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f72f5496000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f72f6600000)
```

However, the bad news is that simply adding this file will not help because of two reasons:

1. `libsz.so` implements the SZIP compression, which has a restrictive license as described in <https://portal.hdfgroup.org/display/HDF5/Szip+Compression+in+HDF+Products>. Thus including it in this NuGet package will probably cause licensing issues.

2. The RPATH of `libhdf5.so` is not set to search for `libsz.so` in the same directory as `libhdf5.so` is located. Thus the Linux dynamic linker will not find `libsz.so`, even if we put it alongside `libhdf5.so`. To fix this, `libhdf5.so` has to be rebuilt with the `-Wl,-rpath=$ORIGIN` option passed to the linker. This can be checked using the `readelf -d <filename>` command.

So we either have to a) ask the HDF group to rebuild the official binaries without SZIP support or b) rebuild them ourselves and possibly get into Linux dependency hell, i.e. checking if the binaries work on all popular distributions due to dependencies.

**Comment by surban** [comment]
I just checked the original HDFGroup/HDF.PInvoke repository. They are also including `szip.dll` in `native/HDF5 1.10/bin64`, but COPYING does not state the SZIP restrictions.

Am I missing something or does the original NuGet package have the same licensing problem?

**Comment by surban** [comment]
I've updated the binaries with a new build, see <https://github.com/surban/hdf5/tree/build-1_10_2/scripts>, and now the tests are passing. I've also removed support for SZIP compression until the licensing issue is cleared up.

Thanks for your contribution!

**Comment by Apollo3zehn** [comment]
For now I think this is the best solution. Today I tried Ubuntu on Windows (thanks for the hint) to load the libsz.so.2 file properly. The only options were to either copy the file into /usr/lib (requires `sudo`) or to set the `LD_LIBRARY_PATH` before the actual application is started. Both ways are not very clean and I am happy that you found a way to solve it. I saw your new NuGet package and will test it tomorrow in my own application.

**Pull request merged**
