### PR TITLE
Update HDF.PInvoke to 1.10.5

### PR DESCRIPTION
**Pull request by Apollo3zehn**
I created a simple merge commit between HDF.PInvoke and your fork to update it to HDF 1.10.5. 

Things I have not changed:
- native_src.txt
- doc/RELEASE_NOTES.md

I do not need the improvements of the new HDF versions, but I would like to keep this repository up to date with the origin to demonstrate how a working .NET Standard implementation of HDF.PInvoke could look like :-)

### CODE REVIEW

**Comment by jjzieve** [comment]
@surban and @Apollo3zehn Thank you both for the work on this effort. Any word on this PR and the larger effort of getting this merged into the HDF group repo?

**Comment by silkfire** [comment]
PR referenced in PR of original repository at HDFGroup/HDF.PInvoke#127

**Comment by surban** [comment]
Thanks for the updated version. I've merged it and currently I am waiting for the native HDF5 build to complete before I can release it.

**Comment by silkfire** [comment]
@Apollo3zehn @surban Could we update the HDF5 binaries to 1.10.6? https://github.com/live-clones/hdf5/releases/tag/hdf5-1_10_6

**Comment by Apollo3zehn** [comment]
As soon as https://github.com/HDFGroup/HDF.PInvoke is updated to 1.10.6 (by @gheber), I will update https://github.com/HDFGroup/HDF.PInvoke.1.10 as well since it is based on that repo. 

I am not sure how @surban prefers to update this repo but I guess he will also wait until the upstream repo is updated. gheber knows best how to add the P/Invoke signtures. Or does 1.10.6 have no new / changed methods? I did not check yet. In that case, updating would be simple.

**Comment by gheber** [comment]
I will start the 1.10.6 update work next week. I need to catch up on the release notes. I think I'm gonna pass on the new VFDs for now (Java dependence for HDFS and `libcurl` dependence for S3). I think there are mostly performance improvements. And then there's is 1.12 coming...

**Pull request merged**
